branch-defaults:
  master:
    environment: Design-FR1-dev
global:
  application_name: Design-FR1
  default_ec2_keyname: dfr
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
